# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_address_first_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='first_line',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
