# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_address_first_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='postcode',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='address',
            name='town',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
